name: sparkpay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.1
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/motions/
    - assets/fonts/
  fonts:
    - family: Lexend Giga
      fonts:
        - asset: assets/fonts/LexendGiga-VariableFont_wght.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
